# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_scc_v2_project_notification_config'
generation_type: 'mmv1'
api_service_name: 'securitycenter.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'NotificationConfig'
