# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_logging_organization_settings'
generation_type: 'mmv1'
api_service_name: 'logging.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'Settings'
