# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_spanner_instance_config'
generation_type: 'mmv1'
api_service_name: 'spanner.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'InstanceConfig'
