# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_app_engine_application_url_dispatch_rules'
generation_type: 'mmv1'
api_service_name: 'appengine.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'Application'
