# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_bigquery_data_transfer_config'
generation_type: 'mmv1'
api_service_name: 'bigquerydatatransfer.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'TransferConfig'
