# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_identity_platform_tenant_default_supported_idp_config'
generation_type: 'mmv1'
api_service_name: 'identitytoolkit.googleapis.com'
api_version: 'v2'
api_resource_type_kind: 'DefaultSupportedIdpConfig'
