# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_cloudbuild_bitbucket_server_config'
generation_type: 'mmv1'
api_service_name: 'cloudbuild.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'BitbucketServerConfig'
