# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_dataproc_gdc_application_environment'
generation_type: 'mmv1'
api_service_name: 'dataprocgdc.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'ApplicationEnvironment'
