# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_firebase_app_check_device_check_config'
generation_type: 'mmv1'
api_service_name: 'firebaseappcheck.googleapis.com'
api_version: 'v1'
api_resource_type_kind: 'DeviceCheckConfig'
